/**
 * Copies contract ABIs from the Foundry build output (evm/out) into typed
 * TypeScript modules under lib/evm/abi/. Run after changing contracts:
 *
 *   (cd evm && forge build) && node scripts/sync-evm-abi.cjs
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const outDir = path.join(root, "evm", "out");
const abiDir = path.join(root, "lib", "evm", "abi");

const targets = [
  {
    artifact: path.join(outDir, 'StableLaunchpad.sol', 'StableLaunchpad.json'),
    file: 'stableLaunchpad.ts',
    exportName: 'stableLaunchpadAbi',
  },
  {
    artifact: path.join(outDir, 'StableLaunchToken.sol', 'StableLaunchToken.json'),
    file: 'stableLaunchToken.ts',
    exportName: 'stableLaunchTokenAbi',
  },
  {
    artifact: path.join(outDir, 'StableLocker.sol', 'StableLocker.json'),
    file: 'stableLocker.ts',
    exportName: 'stableLockerAbi',
  },
  {
    artifact: path.join(outDir, 'StableRouter.sol', 'StableRouter.json'),
    file: 'stableRouter.ts',
    exportName: 'stableRouterAbi',
  },
];

fs.mkdirSync(abiDir, { recursive: true });

for (const t of targets) {
  const artifact = JSON.parse(fs.readFileSync(t.artifact, "utf8"));
  const body = `// Generated by scripts/sync-evm-abi.cjs — do not edit by hand.
export const ${t.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  fs.writeFileSync(path.join(abiDir, t.file), body);
  console.log(`wrote lib/evm/abi/${t.file} (${artifact.abi.length} entries)`);
}

// Creation bytecode of the launch token — the vanity salt miner needs it to
// compute CREATE2 addresses server-side.
for (const t of [
  {
    sol: 'StableLaunchToken.sol',
    json: 'StableLaunchToken.json',
    file: 'stableLaunchTokenBytecode.ts',
    exportName: 'stableLaunchTokenBytecode',
  },
]) {
  const artifact = JSON.parse(fs.readFileSync(path.join(outDir, t.sol, t.json), "utf8"));
  const body = `// Generated by scripts/sync-evm-abi.cjs — do not edit by hand.
export const ${t.exportName} = ${JSON.stringify(artifact.bytecode.object)} as \`0x\${string}\`;
`;
  fs.writeFileSync(path.join(abiDir, t.file), body);
  console.log(`wrote lib/evm/abi/${t.file}`);
}
